- gyft.py
- Passing in password in the CLI makes it visible in `bash_history`
> Get password using getpass.getpass, hidden entry

- add_events.py
- gyft.py
> Included better way to classify as a lab / class

- README.md
A webapp was developed by Nishant to aid the process of getting time table from ERP.
Not everyone would want to clone the repository and run the application on their system and hence it is better to include the link to the currently running web app.
I'll try to add some more features to the webapp and see if it's possible to host it on my DO.
> Update README to include the webapp

- gyft.py
This Fixes the issue #18 
The code is taken from another project [gyft2](https://xypnox.github.io/gyft2/).
> Fixes #18 misaligned Rows :smile: :relaxed:

- add_events.py
- del_events.py
- gyft.py
- requirements.txt
Fixed issue #48 as created by @thealphadollar . Asking user to enter roll number. Modified gyft.py
> Ask username

- add_events.py
- del_events.py
- requirements.txt
Updated Requests requirement in requirements.txt. issue #46 created by @thealphadollar
> updated requests & fixed error for oauth2client in add_events.py

- README.md
- requirements.txt
Updated README.md & urllib3
Mentioned to rename credentials.json to client_secret.json before saving
There is a vulnerability in the urllib3 version we currently used.
Updated it to urllib3>=1.23
Issue #51 created by @thealphadollar resolved
> Updated README.md & urllib3

- dates.py
Added dates for the spring semester of 2018-19. Tested with identical gyft2 also.
> Refreshed dates

- dates.py
I am setting Mid Sem to 19 Sept (Saturday) to 20 Sept(Sunday) just to not break the existing code bcoz of this online sem. Since there are no classes on those days, I expect this to work.
Sem start date = 1st Sept
End = 29th Nov (?)
> Change dates for Autumn 2020-21

- CONTRIBUTING.md
The same spelling mistake exists in many of your projects. I am skimming through all your projects to remove it. Please merge this PR
> Fix Spelling mistake

- dates.py
Spring '21 is here (Online 😢) and it's time to update dates for this semester
Ref: http://iitkgp.ac.in/files/acad_cal2021_all.pdf
> Update dates for Spring 2020-2021 semester

- dates.py
Update 4 reference dates for Spring 21-22
> Update dates.py - Spring 21-22

- dates.py
Signed-off-by: Sahil Shubham <sahil.shubham2000@gmail.com>
> updated dates for 2022-23 Autumn semester;

- dates.py
Attaching screenshots from the academic calendar as well as the calendar itself for reference:
- <img width="640" alt="image" src="https://user-images.githubusercontent.com/62993493/209781173-477ed147-03c7-457b-929b-64dd2f202540.png">
- <img width="691" alt="image" src="https://user-images.githubusercontent.com/62993493/209781219-b59ea6a7-5f3c-498b-893b-184d608fd07f.png">
- <img width="691" alt="image" src="https://user-images.githubusercontent.com/62993493/209781239-522c75b6-ae9b-4823-b5ae-89e2fb5492ae.png">
[Academic Calendar 2022-23.pdf](https://github.com/metakgp/gyft/files/10313057/Academic.Calendar.2022-23.pdf)
> Updated dates for spring semester 2022-23

- README.md
- As the name suggests, updated `README` to reflect the new format of executing
- I have tried to make it as concise as possible while including all cases, but there is still room for improvement, and suggestions are welcome
- Addresses 2nd (and potentially even 3rd) point of #93
> Update README to reflect new format 

- .gitignore
For people who prefer creating a virtual environment
> update gitignore with venv

- CONTRIBUTING.md
Changed communication medium from gitter channel to MetaKGP Slack channel
> Update communication medium in CONTRIBUTING.md

- README.md
- generate_ics.py
- gyft.py
- `--input` flag was removed as it was no longer needed after deletion of `data.txt` as middleware
- also removed one irrelevant comment
> Removed `--input` flag

- README.md
- I have not changed the icon from the template yet.
- Moved the "Updates to be made each sem" section under "Development Notes"
> Updated README(issue #93)

- README.md
- utils/dates.py
dates.py has been updated in accordance to mid term and end term dates of spring semester
> updated dates for spring semester and slight edit in README

- timetable/extractor.py
- Refactored the `build_courses()` code - cleaned up, removed repetitions [see commits for more info]
- Fix: Check for empty cell before checking for empty course code
- Fix: Add the `prev` course to the list at the end of the day only if it is not None
> Some Fixes and Refactoring

- utils/dates.py
- Adjusted the start and end dates to align with the Spring Semester schedule.
Note:
Further testing may be needed to ensure everything works as expected.
> Updated Dates for Spring Semester 2025

- app.py
- timetable/extractor.py
- fix bug by properly passing the string into `get_time()`
- simplify logic of `get_time()`
- fix url of cors in backend for vite server
> [Bug] wrong type passed into get_time
